
name: CI

on:                     # This pipeline is executed when:
  push:                 # - A push event is fired
    branches:           #   over this branches
      - main

  pull_request:         # - A pull request
    branches:           #   over this base branches
      - main
    types:              #   is...
      - opened          #   submitted
      - synchronize     #   or push more commits
      - reopened        #   or reopened after closed (no merged)

permissions:
  # needed to checkouts/branching
  contents: read

# This allows a subsequently queued workflow run to interrupt/wait for previous runs
concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false  # true: interrupt, false = wait for

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup-repo

      - name: Run code linter
        run: |
          npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup-repo

      - name: Run webapp builder
        run: |
          npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}--dist--${{ github.run_id }}
          path: dist

  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup-repo

      - name: Run docs generator
#        continue-on-error: true
        run: |
          npm run generate-docs

      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}--docs--${{ github.run_id }}
          path: docs

  test:
    needs: [lint, build]
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup-repo
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}--dist--${{ github.run_id }}
          path: dist

      - name: Run tests
        run: |
          npm run test
